apiVersion: v1
kind: ServiceAccount
metadata:
  name: citadel-backend
  namespace: citadel
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/citadel-backend-irsa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: citadel-frontend
  namespace: citadel
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/citadel-frontend-irsa
